opt_in_rules:
- empty_count
- empty_string

disabled_rules:
- todo

excluded:
- Carthage
- Pods
- Beskar/Sources/Base/Swinject.swift

trailing_comma:
    mandatory_comma: true

line_length:
    error: 100
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 800
    error: 1000
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

type_name:
    min_length: 1
    max_length: 30

identifier_name:
    min_length: 2
    max_length: 30

nesting:
    type_level:
        warning: 4
        error: 6
    function_level:
        warning: 5
        error: 10

unused_optional_binding:
    ignore_optional_try: true

reporter: "xcode"
