opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods

trailing_comma:
    mandatory_comma: true

line_length:
    error: 100
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 800
    error: 1000
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

type_name:
    min_length: 1
    max_length: 40

reporter: "xcode"
