#!/bin/sh
[ -d scripts ] || (echo "ERROR: Please run script from top folder" && exit 1)
source scripts/helpers
set -e

git diff --diff-filter=d --name-only -- "*.swift" | while read filename; do
    log_info "Running SwiftLint on $filename"
    $SWIFTLINT lint --path "$filename"
done

git diff --cached --diff-filter=d --name-only -- "*.swift" | while read filename; do
    log_info "Running SwiftLint on $filename"
    $SWIFTLINT lint --path "$filename"
done

git ls-files --others --exclude-standard -- "*.swift" | while read filename; do
    log_info "Running SwiftLint on $filename"
    $SWIFTLINT lint --path "$filename"
done

log_success "SwiftLint finished successfully!"
