#!/bin/sh
# Run SpellChecker on changed files

# Check `pwd` and use helpers
[ -d scripts ] || (echo "ERROR: Please run script from top folder" && exit 1)
source scripts/helpers

# Initialize checks
output=""

# Run on staged
while read filename; do
    [[ -z $filename ]] && continue
    log_info "Running SpellChecker on $filename"
    out=$($SPELLCHECK "$filename" | tee /dev/fd/2)
    output="${output}${out}"
done <<< "$(git diff --diff-filter=d --name-only -- "*.swift")"

# Run on chached 
while read filename; do
    [[ -z $filename ]] && continue
    log_info "Running SpellChecker on $filename"
    out=$($SPELLCHECK "$filename" | tee /dev/fd/2)
    output="${output}${out}"
done <<< "$(git diff --cached --diff-filter=d --name-only -- "*.swift")"

# Run on others, exluding deleted
while read filename; do
    [[ -z $filename ]] && continue
    log_info "Running SpellChecker on $filename"
    out=$($SPELLCHECK "$filename" | tee /dev/fd/2)
    output="${output}${out}"
done <<< "$(git ls-files --others --exclude-standard -- "*.swift")"

if [[ $output =~ "warning" ]]; then exit 1; fi
