name: BeskarCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Build & Coverage
    runs-on: macos-latest

    env:
      workspace: 'BeskarWorkspace.xcworkspace'
      scheme: 'Beskar'
      destination: 'platform=iOS Simulator,name=iPhone 12'
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Podfile.lock

      - name: install-pods
        run: pod install
        shell: bash

      - name: build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: ${{ env.workspace }}
          scheme: ${{ env.scheme }}
          destination: ${{ env.destination }}
          action: build

      - name: test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: ${{ env.workspace }}
          scheme: ${{ env.scheme }}
          destination: ${{ env.destination }}
          action: test
          enable-code-coverage: true

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash -J ${{ env.scheme }} -t ${{ env.codecov_token }})

  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: install-mint
        shell: bash
        run: brew install mint

      - name: mint-bootstrap
        shell: bash
        run: mint bootstrap

      - name: lint-all
        shell: bash
        run: ./scripts/lint_all
